<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice_temp2_model extends Model
{
    use HasFactory;
    protected $table="invoice_temp2";
    protected $fillable = ['BILLING_DOCUMENT','BILLING_DATE','BILLING_DOCUMENT_TYP','BILLING_DES','COMPANY_CODE','SALES_ORDER','SALES_ORDER_ITEM','CUSTOMER_NO','CUSTOMER_NAME',
    'CUSTOMER_PO_No','CUSTOMER_PO_Date','SALES_ORGANISATION','DISTRIBUTION_CHANNEL','DIVISION','PLANT','ITEM_CODE','MATERIAL_NAME','MATERIAL_DESCRIPTION',
    'CUSTOMER_PART_NUMBER','CUSTOMER_PART_NME','INCOTERMS','HSN/SAC','COUNTRY_NAME','REGION','ITEM_VALUE','DISCOUNT__PERCENT','BILLED_QTY','ITEM_TOTALVALUE',
    'DISCOUNTED_VALUE','TOTAL_VALUE_AFTER_DI','CURRANCY','FI_DOCUMENT','EXCHANG_RATE','FINAL_VALUE','JOIG_PERCENT','JOIG_TAX_VALUE','JOCG_PERCENT','JOCG_TAX_VALUE',
    'JOSG_PERCENT','JOSG_TAX_VALUE','TOTAL_TAX_ITEM_WISE','PACKING_COST','TOTAL_PACKING_COST','TOTAL_TCS/SALE','TCS_TAX/SALES_PERCENT','TCS_TAX_/SCRAP_PERCENT',
    'TOTAL_TCS/SCRAP','TOTAL_INV_VALUE','IRN_NO','TRANSPORTER_NAME','TRANSPORT_MODE','TRANSPORTER_NO','TRANSPORT_DATE',
    'VECHILE_NO','EWAY_BILL_NO','EWAY_BILL_DT','LR_NO','LR_DATE','GRN_NO','GRN_DATE','REMARKS',];
    
}
